parameters:
- name: "testplan"
  type: string
  default: ""
 
trigger:
- main

resources:
  webhooks:
    - webhook: "XrayWebhookTrigger"             ### Webhook alias
      connection: "XrayWebhookConnection"       ### Incoming webhook service connection

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet restore
  displayName: 'install build dependencies'

- script: |
    dotnet test -s nunit.runsettings
  displayName: 'Run tests'
  
- task: Maven@3
  inputs:
    mavenPomFile: 'java-junit-calc/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17.0.7'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean compile test'
- bash: |
    token=$(curl -H "Content-Type: application/json" -X POST --data '{ "client_id": "$(client_id)","client_secret": "$(client_secret)" }' https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
    curl -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer ${token}" --data @java-junit-calc/target/surefire-reports/pom.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=$(project_key)
